### ISSUE TITLE
File ".working_set_socket" exists.

### ISSUE THREAD

**Issue by andyjessop** [coderifous/working_set#2]
Amazing program, thanks so much for making it available. I'm now using it as part of my daily setup.

I have a script that loads up working set automatically, but occasionally (when I haven't shut it down correctly?) I get this error message, and have to enter `y` into the console to overwrite.

Is there a way to avoid this? Perhaps an overwrite-by-default flag? 

Or perhaps I can delete the file manually before opening.

**Comment by coderifous** [comment]
Hi Andy - thank you for the kind words!  That file is left behind in the event that working_set does not shutdown cleanly, e.g. in the event of a computer crash.  It is safe to delete it.

My only hesitation for adding a flag to overwrite-if-needed is: it shouldn't happen frequently at all.  Can you share your usage pattern?  I wonder why the file is left behind for you - it's normally cleaned up when working_set exits.

**Comment by andyjessop** [comment]
I'm using it inside a tmux session and I just kill the session. When I create a new session, the file mist still exist.

Today I just added a script to delete that file before creating the session, so it's not an issue for me now.

**Comment by coderifous** [comment]
> I just kill the session

Brutal but efficient.  That explains that.  I'll see if there's a way I can have working_set handle that kind of shutdown context gracefully.  Thanks for the info!
